version: '3.8'

services:
  app:
    build: .
    container_name: healthpick-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - healthpick-network

  nginx:
    image: nginx:alpine
    container_name: healthpick-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - healthpick-network

networks:
  healthpick-network:
    driver: bridge 